Add/reference system
eurodatacube/public-collections pull request #186
Opened 2022-03-16 14:16 UTC by dthiex

- added reference_system to have something there (might need to be updated once we get the correct info from Matic who is currently on holiday)
- corrected steps in the temporal extend to match those of the collections description/other info

2022-03-16 16:00 UTC, zcernigoj requested changes

2022-03-16 16:00 UTC, zcernigoj commented on collections/sentinel-s2-l2a-mosaic-120.yaml
> +      $schema: https://proj.org/schemas/v0.4/projjson.schema.json
Can't find where you got this CRS, but since it's more as a placeholder, this comment can be ignored.

2022-03-16 17:26 UTC, dthiex commented on collections/sentinel-s2-l2a-mosaic-120.yaml
> -    step: P5D
In theory yes "will be" but this collection only holds data for 1 year so far so should imo be added once more data has been added.

2022-03-17 07:57 UTC, zcernigoj commented on collections/sentinel-s2-l2a-mosaic-120.yaml
> -    step: P5D
Ah that's also true. Let's add it once more data will be added.

2022-03-17 07:57 UTC, zcernigoj approved these changes

2022-03-17 07:58 UTC, merged