Update collection ids for collections that were moved from mundi to services.sentinel-hub.com
eurodatacube/public-collections pull request #189
Opened 2022-04-01 06:12 UTC by Dorothyrono

- these collections were moved to a new bucket in aws , there they are updated regularly

2022-04-14 12:33 UTC, dthiex requested changes

2022-04-15 06:45 UTC, dthiex commented on collections/s5p-no2-tropno-daily-check.yaml
> +   CollectionId: 972e67a7-2ca8-4bf6-964a-11fe772e3ac2
Not sure what went wrong with checking but I just saw that there is also more recent data here (2022-03-28) so this seemed to have worked.

2022-04-15 08:33 UTC, dthiex commented on collections/chl_water_quality_saturday.yaml
> +TemporalAvailability: 2020-01-04 - ongoing
@AlessandroScremin Do you maybe know how regularly the chl_water_quality_saturday collection is updated?

2022-04-21 09:34 UTC, AlessandroScremin commented on collections/chl_water_quality_saturday.yaml
> +TemporalAvailability: 2020-01-04 - ongoing
@dthiex 
Sorry, for the late replay.
These collections are updated every week, the last delay was due to the migration from Mundi to aws of all the collections.

SO please keep weekly update frequency (but in some exceptions they could be delayed)

2022-04-21 10:30 UTC, AlessandroScremin commented
From My Side they are fine

@Schpidi

2022-04-21 10:31 UTC, AlessandroScremin approved these changes
They are fine from my side

@Schpidi

2022-04-26 08:31 UTC, dthiex commented on collections/chl_water_quality_saturday.yaml
> +TemporalAvailability: 2020-01-04 - ongoing
Great, thanks for the answer! Checked and there are now also later products (e.g. 2022-04-09) available so things seem to work correctly.

2022-04-26 08:32 UTC, dthiex approved these changes

2022-04-26 08:32 UTC, merged