Display correct IDs for openEO collections
eurodatacube/public-collections pull request #266
Opened 2022-12-08 14:04 UTC by horvatdino

Closes #259 

This PR:
- Updates the following collections with the OpenEOPID:
  - `co_3daily_data`
  - `s5p-ch4_weekly`
  - `so2_daily_data`
- Removes `phytoplankton-primary-production` from the index endpoint

2022-12-09 12:09 UTC, dthiex requested changes

2022-12-09 13:31 UTC, horvatdino commented on collections/co_3daily_data.yaml
>        - co
You're right. Changed to `P1D`.

2022-12-09 13:31 UTC, horvatdino commented on collections/so2_daily_data.yaml
> +OpenEOPID: SENTINEL_5P_CH4_T1D
Removed.

2022-12-09 13:31 UTC, horvatdino commented on collections/s5p-ch4-weekly.yaml
>      values:
Waiting for the response.

2022-12-12 09:02 UTC, horvatdino commented on collections/s5p-ch4-weekly.yaml
>      values:
Dorothy confirmed that this is a regularly updated collection, so this was updated to `null`.

2022-12-12 11:17 UTC, dthiex approved these changes

2022-12-12 11:46 UTC, merged