ghsl-urban-delineation
eurodatacube/public-collections pull request #275
Opened 2023-01-23 21:51 UTC by eorlitova

ghsl-urban-delineation folder  and ghsl-urban-delineation.yaml  first draft

2023-01-25 22:05 UTC, Schpidi commented
thanks @eorlitova, this looks great to me.

@Dorothyrono are you the right person to ask to merge this? thanks

2023-01-27 17:02 UTC, Dorothyrono requested changes

2023-01-31 12:27 UTC, Dorothyrono commented on collections/ghsl-urban-delineation.yaml
> +        Code: 21
@eorlitova 
A suggestion that could work for now, is to introduce a space in the names 
e.g if you add a space just before EPSG...   `HDC_UrbanCentre_ EPSG4326_RefYear.shp` it breaks the name and the table is displayed in much better  way

![image](https://user-images.githubusercontent.com/49271738/215757478-4ffdd4a1-f647-433b-abce-e05edd0e0108.png)

2023-01-31 18:42 UTC, eorlitova commented
@Dorothyrono thanks for your comments.  I have made changes according to them.

2023-01-31 19:00 UTC, eorlitova commented
@Dorothyrono could you please let me know if you can now merge the  ghsl-urban-delineation to the public-collections.
Thanks. Erika

2023-02-01 08:26 UTC, Dorothyrono approved these changes

2023-02-01 08:26 UTC, Dorothyrono commented
Merging

2023-02-01 08:27 UTC, merged