Feat/add mlhub labels
eurodatacube/public-collections pull request #304
Opened 2023-09-21 10:43 UTC by chorng

* add microsoft floods collection
* add south africa crop type competition collection
* add plantvillage crop type kenya collection
* add western usa live fuel moisture collection

2023-09-22 13:12 UTC, Dorothyrono requested changes

2023-09-25 07:40 UTC, chorng commented
@Dorothyrono Fixed the typos and doubled check. Please review again.

2023-09-25 13:56 UTC, Dorothyrono commented on collections/south-africa-crops-competition.yaml
> +  The South Africa Crop Type Competition is a dataset produced as part of the [Radiant Earth Spot the Crop Challenge](https://zindi.africa/hackathons/radiant-earth-spot-the-crop-hackathon). This data
doubel check, not resolved

2023-09-25 13:56 UTC, Dorothyrono commented on collections/south-africa-crops-competition/README.MD
> +The South Africa Crop Type Competition is a dataset produced as part of the [Radiant Earth Spot the Crop Challenge](https://zindi.africa/hackathons/radiant-earth-spot-the-crop-hackathon). This datase
double check, not resolved

2023-09-25 13:57 UTC, Dorothyrono commented on collections/western-usa-fuel-moisture.yaml
> +  The Western USA Live Fuel Moisture is a dataset manually collected in the western United States by the United States Forest Sercice. Live fuel moisture represents the mass of water in live vegetati
doubel check, not fully resolved

2023-09-25 14:02 UTC, Dorothyrono commented on collections/western-usa-fuel-moisture.yaml
> +Provider: "Stanford University"
Looks better with `and`

"Stanford University and [Source Cooperative](https://beta.source.coop/repositories/stanford/sar-moisture-conent/description)"

2023-09-25 14:02 UTC, Dorothyrono commented on collections/western-usa-fuel-moisture/README.MD
> +The Western USA Live Fuel Moisture is a dataset manually collected in the western United States by the United States Forest Sercice. Live fuel moisture represents the mass of water in live vegetation
dobel check, not fully resolved

2023-09-25 14:20 UTC, chorng commented
Done.

2023-09-26 10:08 UTC, Dorothyrono approved these changes

2023-09-26 10:08 UTC, Dorothyrono commented
Looks good. Can merge

2023-09-26 11:42 UTC, merged